### ISSUE TITLE
Accuracy for cross corpus data like interviews

### ISSUE THREAD

**Issue by VSK02101996** [soul0101/Speech-Emotion-Recognition#2]
How is model working for cross corpus data like call center, interviews , reviews etc. ? What is scope of model ?

**Comment by soul0101** [comment]
The speech emotion classifier model used in this daisi is referenced in this research paper:
[Multimodal Emotion Recognition](https://www.overleaf.com/read/xvtrrfpvzwhf). 
You can skip to page 29 which talks about the performance of the model.

**Comment by VSK02101996** [comment]
Required permission to open the research paper. Please upload pdf if you have. @soul0101

**Comment by soul0101** [comment]
Updated the link with a working one! @VSK02101996
